version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env # if you use any environment variables
    volumes:
      - ./backend:/app # optional: live-reload your code
    command: >
      uvicorn main:app
      --host 0.0.0.0
      --port 8000
